<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/03/17 09:02:55

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=upgrader',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
