<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/03/17 10:01:56

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;port=3306;dbname=vos_demo',
  'username' => 'root',
  'password' => NULL,
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
