<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/03/22 10:21:05

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;port=3306;dbname=HRM_UAT',
  'username' => 'sa',
  'password' => 'sa',
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
